Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Empty array of size 2x2
empty_arr = np.empty((2, 2))
empty_arr


array([[1.07409524e-315, 0.00000000e+000],
       [9.04115220e+271, 1.02124020e+277]])

In [ ]:
# 2. All-one array of size 4x2
ones_arr = np.ones((4, 2))
ones_arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 3. Array filled with a specific value using np.full
full_arr = np.full((3, 3), 7)  # example: fill with 7
full_arr


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 4. Zeros with same shape/type as another array
sample_arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(sample_arr)
zeros_like_arr


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 5. Ones with same shape/type as another array
ones_like_arr = np.ones_like(sample_arr)
ones_like_arr


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
converted_arr = np.array(new_list)
converted_arr


array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# 1. Array with values 10 to 49
arr_10_49 = np.arange(10, 50)
arr_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# 2. 3x3 matrix with values 0–8
matrix_0_8 = np.arange(9).reshape(3, 3)
matrix_0_8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 3. Identity matrix 3x3
identity_3 = np.eye(3)
identity_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4. Random array of size 30 and its mean
rand_arr = np.random.random(30)
rand_mean = rand_arr.mean()
rand_mean

np.float64(0.47894387011200734)

In [ ]:
# 5. 10x10 random array (min & max)
arr_10x10 = np.random.random((10, 10))
arr_min = arr_10x10.min()
arr_max = arr_10x10.max()

arr_min, arr_max

(np.float64(0.009160013448249127), np.float64(0.9969926011746717))

In [ ]:
# 6. Zero array of size 10 and replace 5th element
zero_arr = np.zeros(10)
zero_arr[4] = 1
zero_arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
reversed_arr

array([0, 4, 0, 0, 2, 1])

In [ ]:
# 8. 2D array: border = 1, inside = 0
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
border_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 9. 8x8 checkerboard pattern
checker = np.zeros((8, 8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
checker

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
# 1. Add x and y
add_xy = np.add(x, y)
add_xy

array([[ 6,  8],
       [10, 13]])

In [ ]:
# 2. Subtract x and y
sub_xy = np.subtract(x, y)
sub_xy

array([[-4, -4],
       [-4, -3]])

In [ ]:
# 3. Multiply x with any integer
mul_x = x * 3
mul_x

array([[ 3,  6],
       [ 9, 15]])

In [ ]:
# 4. Square of each element in x
square_x = x ** 2
square_x

array([[ 1,  4],
       [ 9, 25]])

In [ ]:
# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

dot_vw, dot_xv, dot_xy

(np.int64(219),
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [ ]:
# 6. Concatenate x & y (rows) and v & w (columns)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
concat_xy_row, concat_vw_col

(array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [ ]:
# 7. Concatenate x and v → ERROR explanation
# x is 2x2 matrix; v is 1D vector of size 2
# shapes are incompatible for direct concatenation along any axis.

Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= B.
3. Prove (AB)^T = B^T A^T
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9


{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
# Matrix A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [ ]:
# Prove A . inverse of A = I
A_inv = np.linalg.inv(A) # Inverse of A
I = np.dot(A, A_inv) # Product of A and its inverse
I

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [ ]:
#Prove AB ̸= B
AB = A @ B
BA = B @ A
AB, BA #compare

(array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]))

In [ ]:
#Prove (AB)^T = B^T A^T
lhs = (A @ B).T # transpose of (AB)
rhs = B.T @ A.T # B transpose times A transpose
lhs, rhs # compare

(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

System:  
2x – 3y + z  = -1     

x – y + 2z   = -3

3x + y – z   = 9

In [ ]:
# Coefficient matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

# Constant matrix B
B = np.array([-1, -3, 9])

In [ ]:
# Solve using inverse
A_inv = np.linalg.inv(A) # inverse of A
X = A_inv @ B
X

array([ 2.,  1., -2.])

In [ ]:
# Solve using np.linalg.solve
X2 = np.linalg.solve(A, B)
X2

array([ 2.,  1., -2.])

Experiment: How Fast is Numpy?
1. Element-wise Addition:    

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

3. Dot Product   
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.  

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Python lists with 1 million numbers
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

In [ ]:
# Element-wise Python list addition
start = time.time()
py_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python addition time:", end - start)

Python addition time: 0.042130231857299805


In [ ]:
# Element-wise Numpy addition
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
np_add = arr1 + arr2
end = time.time()
print("Numpy addition time:", end - start)

Numpy addition time: 0.0018041133880615234


In [ ]:
# Element-wise Python multiplication
start = time.time()
py_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python multiplication time:", end - start)

Python multiplication time: 0.05521893501281738


In [ ]:
# Element-wise Numpy multiplication
start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("Numpy multiplication time:", end - start)

Numpy multiplication time: 0.0032820701599121094


In [ ]:
# Python dot product (manual)
start = time.time()
py_dot = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python dot time:", end - start)

Python dot time: 0.05859827995300293


In [ ]:
# Numpy dot product
start = time.time()
np_dot = np.dot(arr1, arr2)
end = time.time()
print("Numpy dot time:", end - start)

Numpy dot time: 0.0037152767181396484


In [ ]:
# Python matrix multiplication (slow)
import random

# Create matrices with random numbers using lists
matrix1 = [[random.random() for _ in range(1000)] for _ in range(1000)]
matrix2 = [[random.random() for _ in range(1000)] for _ in range(1000)]

start = time.time()

# Manual multiplication using nested loops
result = [[sum(a * b for a, b in zip(row, col))
           for col in zip(*matrix2)] for row in matrix1]

end = time.time()

print("Python matrix multiplication time:", end - start)


In [ ]:
# Numpy matrix multiplication (fast)
mat1 = np.random.random((1000, 1000))
mat2 = np.random.random((1000, 1000))

start = time.time()
result_np = mat1 @ mat2
end = time.time()

print("Numpy matrix multiplication time:", end - start)

Numpy matrix multiplication time: 0.04576301574707031
